### ISSUE TITLE
GUI tests

### ISSUE THREAD

**Issue by ppdewolf** [sdcTools/checkTauArgus#2]
Apparently the directory structure of the directories for the GUI tests has changed?

Using the GUItests.Rmd in the vignettes subdirectory gives 404 errors on the files (input and expected output).
In the inst/doc directory there is another GUItests.Rmd (the "old" one with only one test) and some GUItest.html. The required input and expected output are located in this directory.

We should make things consistent?

**Comment by bernhard-da** [comment]
Hi, thx for pointing that out. The relevant file for the vignette is `vignettes/GUItests.Rmd` to describe the tests. Any data-files (optionally) must go to `inst/doc/` directory.

Once the package is installed (eg. `devtools::install(build_vignettes=TRUE)` as described in the README, the vignette from the vignettes-folder is recompiled and resulting files (html, rmd,..) are also copied to `inst/doc/`. I probably forgot to remove them after merging the latest examples which I now did.
